spring:
  application:
    name: coffeemachine
  datasource:
    url: jdbc:mysql://localhost:3306/coffeesmachine?createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
management:
  endpoints:
    web:
      exposure:
        include: '*'
greeting:
  name: Dakota
  coffee: ${greeting.name} is drinking Cafe Cereza
logging:
  level:
    org:
      formation:
        controller:
          CoffeeController: error
account:
  message: "Welcome to Coffee App"
  details:
    name: "Bob"
    email: "f4ba5ce80a5026d3445c6ae2d0a708d649039956f1134a6ed719553e26d9c5cb"
  phone:
  - 0505050505
  - 0606060606
build:
  version: "1.0"